version: "3.9"
services:
  app:
    image: tabelog-custom
    build:
      dockerfile: ./scraping/Dockerfile
      args:
        - target=dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
